services:
  cron-manager:
    build: .
    ports:
      - "8000:8000"
    privileged: true
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - /var/spool/cron:/var/spool/cron
      - /etc/cron.d:/etc/cron.d
    environment:
      - PYTHONPATH=/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/jobs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cron-manager-network

networks:
  cron-manager-network:
    driver: bridge 
